spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    properties:
      schema.registry.url: http://localhost:8081

sensor:
  plant-id: plant01
  sensor-id: sensor01
  interval-ms: 10000
  min-value: 0
  max-value: 100
