spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    properties:
      schema.registry.url: http://localhost:8081

motor:
  plant-id: plant01
  motor-id: motor001
  max-interval-ms: 30000
  states:
    - "on"
    - "off"
